spec:
  inputs:
    microservice-name:
      type: string
    directory-name:
      type: string

---

image: "docker:latest"

variables:
  DOCKER_BUILDKIT: 1
  IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

stages:
  - install
  - build
  - test
  - package
  - release
  - deploy


install-dependencies:
  stage: install
  script:
  - echo "Install dependencies"
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

build-images:
  stage: build
  script:
  - echo "Building images"
  needs:
  - job: install-dependencies
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

unit-test:
  stage: test
  script:
  - echo "Unit test"
  needs:
  - job: build-images
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

integration-test:
  stage: test
  script:
  - echo "Integration test"
  needs:
  - job: unit-test
  - job: build-images
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

component-test:
  stage: test
  script:
  - echo "Component test"
  needs:
  - job: integration-test
  - job: build-images
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

functional-test:
  stage: test
  script:
  - echo "Functional test"
  needs:
  - job: component-test
  - job: build-images
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

package:
  stage: package
  script:
  - echo "Packaging"
  needs:
  - job: build-images
    artifacts: true
  - job: functional-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

deliver-to-registry:
  stage: release
  script:
  - echo "Deliver to registry"
  needs:
  - job: package
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

deploy-chart:
  stage: deploy
  script:
  - echo "Deploy chart to environment"
  needs:
  - job: deliver-to-registry
    artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"