apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - {{ .Values.accessMode }}
  nfs:
    server: {{ .Values.nfsServer }}
    path: {{ .Values.nfsPath }}
