services:
  scheduler:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - broker
    networks:
      - db-network
      - redis-network
      - bus-network
    env_file:
      - .env.docker
    environment:
      - ENV_MODE=production
  db:
    image: "postgres"
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - db-network
      - default
  cache:
    image: "redis"
    env_file:
      - .env.docker
    networks:
      - redis-network
    volumes:
      - cache-data:/data
  broker:
    image: apache/kafka:latest
    container_name: broker
    env_file:
      - .env.local.kafka
    ports:
      - "9092:9092"
    volumes:
      - broker-data:/var/lib/kafka/data
    networks:
      - default
      - bus-network

networks:
  db-network:
    driver: bridge
  bus-network:
    driver: bridge
  redis-network:
    internal: true

volumes:
  db-data:
  cache-data:
  broker-data: