repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: signoz
    url: https://charts.signoz.io

releases:
  # Scheduler
  - name: sch-db
    namespace: scheduler
    chart: bitnami/postgresql
    version: 16.2.2
    values:
      - auth:
          database: {{ requiredEnv "SCHEDULER_POSTGRES_DB" }}
          username: {{ requiredEnv "SCHEDULER_POSTGRES_USER" }}
          password: {{ requiredEnv "SCHEDULER_POSTGRES_PASSWORD" }}
      - persistence:
          primary:
            size: "2Gi"
      - replication:
          enabled: false
      - metrics:
          enabled: false # No se si queremos esto
      - global:
          defaultStorageClass: "local-path"
  - name: scheduler-broker
    namespace: scheduler
    chart: bitnami/kafka
    version: 31.0.0
    values:
      - kraft:
          clusterId: "1"
      - broker:
          replicaCount: 2
      - controller:
          replicaCount: 1
          controllerOnly: false
      - global:
          defaultStorageClass: "local-path"
      - controller:
          persistence:
            size: 2Gi
      - broker:
          persistence:
              size: 2Gi
      - listeners:
          client:
            containerPort: 9092
            protocol: PLAINTEXT
            name: BROKER
          controller:
            containerPort: 9093
            protocol: PLAINTEXT
            name: CONTROLLER
      - provisioning:
          numPartitions: 3
          replicationFactor: 1
      - extraEnvVars:
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: BITNAMI_DEBUG
            value: "true"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
  - name: scheduler
    namespace: scheduler
    chart: ./scheduler
    values:
      - image:
          tag: "dev"
      - scheduler_db_host: "sch-db-postgresql"
      - scheduler_db_user: {{ requiredEnv "SCHEDULER_POSTGRES_USER" }}
      - scheduler_db_pass: {{ requiredEnv "SCHEDULER_POSTGRES_PASSWORD" }}
      - scheduler_db_db: {{ requiredEnv "SCHEDULER_POSTGRES_DB" }}
      - kafka_host: "scheduler-broker-kafka"
      - kafka_port: "9092"
      - submission_kafka_topic: "execution_submissions"
      - steps_kafka_topic: "execution_steps"
      - redis_host: "localhost"
      - submissions_topic: "execution_submissions"
      - steps_topic: "execution_steps"
      - native_host: "scheduler-broker-kafka"
      - native_port: "9092"
      - native_topic: "native_tasks"
      - native_output_topic: "native_task_output"
      - service_host: "scheduler-broker-kafka"
      - services_file_path: "/data/services.json"
      - pvc:
            name: "scheduler-pv"
            accessMode: "ReadWriteMany"
            size: "2Gi"
            label: "nfs-storage"
      - volumes:
          - name: "scheduler-pv"
            persistentVolumeClaim:
              claimName: "scheduler-pv"
      - volumeMounts:
          - name: "scheduler-pv"
            mountPath: "/data"
            readOnly: false

  # Workflow Manager
  - name: wf-db
    namespace: workflow-manager
    chart: bitnami/postgresql
    version: 16.2.2
    values:
      - auth:
          database: {{ requiredEnv "WORKFLOWS_POSTGRES_DB" }}
          username: {{ requiredEnv "WORKFLOWS_POSTGRES_USER" }}
          password: {{ requiredEnv "WORKFLOWS_POSTGRES_PASSWORD" }}
      - persistence:
          primary:
            size: "2Gi"
      - replication:
          enabled: false
      - metrics:
          enabled: false # No se si queremos esto
      - global:
          defaultStorageClass: "local-path"
  - name: workflow-manager
    namespace: workflow-manager
    chart: ./workflow-manager
    values:
      - image:
          tag: "dev"
      - workflows_db_host: "wf-db-postgresql"
      - workflows_db_user: {{ requiredEnv "WORKFLOWS_POSTGRES_USER" }}
      - workflows_db_pass: {{ requiredEnv "WORKFLOWS_POSTGRES_PASSWORD" }}
      - workflows_db_db: {{ requiredEnv "WORKFLOWS_POSTGRES_DB" }}
      - submission_kafka_host: "scheduler-broker-kafka.scheduler.svc.cluster.local"
      - submission_kafka_topic: "execution_submissions"
  # native-service
  - name: native-service
    namespace: native-service
    chart: ./native-service
    values:
      - image:
          tag: "dev-"
      - kafka_host: "scheduler-broker-kafka.scheduler.svc.cluster.local"
      - kafka_port: "9092"
      - input_topic: "native_tasks"
      - output_topic: "native_task_output"
  - name: traefik
    namespace: default
    chart: traefik/traefik
    values:
      - traefik.yaml
  - name: shared-nfs
    namespace: default
    chart: ./nfs-pv
    values:
      - name: "shared-nfs-pv"
      - appLabel: "nfs-storage"
      - storage: "6Gi"
      - accessMode: "ReadWriteMany"
      - nfsServer: {{ requiredEnv "NFS_SERVER" }}
      - nfsPath: "/mnt/nfs"
  - name: logging
    namespace: default
    chart: signoz/signoz
    values:
      - installCRDs: true
      - global:
          storageClass: "local-path"
      - clickhouse:
          persistence:
            size: 2Gi
  - name: logging-ingress
    namespace: default
    chart: ./signoz-ingress
  - name: local-storage-provisioner
    namespace: local-path-storage
    chart: ./local-path-provisioner
    values:
      - storageClass:
          name: "local-path"
