services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
      - broker
    networks:
      - db-network
      - bus-network
    env_file:
      - .env.local
  db:
    image: "postgres"
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - db-network
  broker:
    image: apache/kafka:latest
    container_name: broker
    env_file:
      - .env.local.kafka
    ports:
      - "9092:9092"
    networks:
        - bus-network
    volumes:
      - broker-data:/var/lib/kafka/data

networks:
  db-network:
    internal: true
  bus-network:
    driver: bridge

volumes:
  db-data:
  broker-data: