apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: routes
  namespace: scheduler
spec:
  routes:                          
  - kind: Rule
    match: PathPrefix(`/executions`) && Host(`workflow-manager.local`) && Method(`GET`)
    services:                       
    - kind: Service
      name: scheduler
      port: 8080
