services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network
      - default
#      - service-registry_bus-network
    env_file:
      - .env.local
  db:
    image: "postgres"
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - db-network

networks:
  db-network:
    internal: true
#  scheduler_bus-network:
#    external: true

volumes:
  db-data: