services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network
      - default
    env_file:
      - .env.local
  db:
    image: "postgres"
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - db-network
      - default

networks:
  db-network:
    driver: bridge

volumes:
  db-data: